---

- hosts: all
  become: true
  tasks:

  - name: update repository index for Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache for Ubuntu
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index for AlmaLinux
    dnf:
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"

  - name: install httpd package for AlmaLinux
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: install php for AlmaLinux
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "AlmaLinux"
