---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes 
    when: ansible_distribution == "Ubuntu"

  - name: install updates (AlmaLinux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"
        

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages (AlmaLinux)
    tags: apache,apache2,almalinux
    dnf:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == "AlmaLinux"


  - name: copy default html page
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644  


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (AlmaLinux)
    tags: db,mariadb,almalinux
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
