---

- hosts: all
  become: true
  pre_tasks:

  - name: update cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false 
    when: ansible_distribution == "Ubuntu"

  - name: update cache (AlmaLinux)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "AlmaLinux"


- hosts: all
  become: true
  tasks:
    
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEInALiSzd4UWNOEZqma8MogK9O0hnmZPuco+U4pYOkg ansible"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    when: ansible_distribution == "Windows"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages (AlmaLinux)
    tags: apache,apache2,almalinux
    dnf:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

  
  - name: start httpd service (AlmaLinux)
    tags: httpd,apache,almalinux
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "AlmaLinux"

  - name: change e-mail address for admin (AlmaLinux)
    tags: apache,apache2,httpd,almalinux
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin reenat_2.0@mail.ru
    when: ansible_distribution == "AlmaLinux"
    register: httpd_play

  
  - name: restart httpd (AlmaLinux)
    tags: apache,apache2,httpd,almalinux
    service:
      name: httpd
      state: restarted
    when: httpd_play.changed


  - name: copy default html page
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644  


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (AlmaLinux)
    tags: db,mariadb,almalinux
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
