- name: install apache and php packages
  tags: apache,apache2,ubuntu
  package:
    name:
    - "{{ apache_package_name }}"
    - "{{ php_package_name }}"
    state: latest

- name: start httpd service
  tags: httpd,apache,almalinux
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin (AlmaLinux)
  tags: apache,apache2,httpd,almalinux
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin reenat_@mail.ru
  when: ansible_distribution == "AlmaLinux"
  notify: restart_apache
  
- name: copy default html page
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644  
