- name: install apache and php packages (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
    - apache2
    - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php packages (AlmaLinux)
  tags: apache,apache2,almalinux
  dnf:
    name:
    - httpd
    - php
    state: latest
  when: ansible_distribution == "AlmaLinux"
  
- name: start httpd service (AlmaLinux)
  tags: httpd,apache,almalinux
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "AlmaLinux"

- name: change e-mail address for admin (AlmaLinux)
  tags: apache,apache2,httpd,almalinux
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin reenat_2.0@mail.ru
  when: ansible_distribution == "AlmaLinux"
  register: httpd_play
  
- name: restart httpd (AlmaLinux)
  tags: apache,apache2,httpd,almalinux
  service:
    name: httpd
    state: restarted
  when: httpd_play.changed

- name: copy default html page
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644  
